export const AGENDIFY_API_ROUTES = {
  USER: '/users',
  BUSINESS: '/business',
  ADDRESS: '/address',
  AVAILABILITY: '/availability',
  AVAILABILITY_BY_BUSINESS: '/availability/business',
  RATING: '/rating',
  MY_RATINGS: '/rating/my-ratings',
  SERVICE: '/services',
  MY_BUSINESS: '/business/my-business',
  LOGIN: '/login',
  ME: '/users/me',
  SERVICES_BY_BUSINESS: '/services/get-by-business',
  UPDATE_SERVICE_IMAGE: '/services/setImage',
  UPDATE_BUSINESS_IMAGE: '/business/setImage',
} as const;
