export const APP_ROUTES = {
  LOGIN: '/',
  REGISTER_USER: '/registerUser',
  MANAGER_USER: '/session/manageUser',
  SEARCH_BUSINESS: '/session/searchBusiness',
  MY_BUSINESS_LIST: '/session/myBusiness',
  REGISTER_BUSINESS: '/session/registerBusiness',
  MANAGE_SERVICE: '/session/service/manage',
  REGISTER_SERVICE: '/session/service/register',
  MY_SCHEDULE: '/session/mySchedule',
  MANAGE_MY_BUSINESS: '/session/manageMyBusiness',
  VIEW_MY_BUSINESS: '/session/myBusiness',
  MY_AVAILABILITY: '/session/myAvailability',
  VIEW_BUSINESS: '/session/viewBusiness',
  SCHEDULE: '/session/schedule',
} as const;
